# Generated by Django 4.2.1 on 2023-05-17 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=30, unique=True)),
                ("password", models.CharField(max_length=30)),
                ("role", models.CharField(max_length=30)),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SocietyMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=30)),
                ("lastname", models.CharField(max_length=30)),
                ("house_no", models.CharField(max_length=10)),
                ("contact_no", models.CharField(max_length=30)),
                ("blood_group", models.CharField(max_length=5)),
                ("job_description", models.CharField(max_length=60)),
                ("work_address", models.TextField()),
                ("no_of_family_address", models.CharField(max_length=30)),
                ("vehicle_details", models.CharField(max_length=60)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Chairman.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Chairman",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=30)),
                ("lastname", models.CharField(max_length=30)),
                ("house_no", models.CharField(max_length=10)),
                ("contact_no", models.CharField(max_length=30)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Chairman.user"
                    ),
                ),
            ],
        ),
    ]
