# Generated by Django 4.2.1 on 2023-05-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Chairman", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chairman",
            name="pic",
            field=models.FileField(
                default="media/images/user.png", upload_to="media/images"
            ),
        ),
        migrations.AddField(
            model_name="societymember",
            name="pic",
            field=models.FileField(
                default="media/images/user.png", upload_to="media/images"
            ),
        ),
    ]
